#!/usr/bin/env bash
# shellcheck disable=SC1091

set -euo pipefail
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
. 'script/utils.sh'

. script/import.sh

case "$PLATFORM" in
    darwin)
        h1 'Mac dveloper tools'
        h2 'Enable developer mode'
        run DevToolsSecurity -enable
        h2 'Install Xcode command line tools'
        run_ignore_errors xcode-select --install

        h1 'Homebrew'
        if command -v brew; then
            h2 'Update Homebrew'
            run brew update
        else
            h2 'Install Homebrew'
            /usr/bin/env bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        fi
        h2 'Install Homebrew formulas'
        run brew bundle
        ;;
    linux)
        exit_failure 'Linux is not currently supported'
        ;;
    windows)
        exit_failure 'Windows is not currently supported'
        ;;
esac

# h1 'git'
# h2 'Update submodules'
# run git submodule update --init --recursive

script/install_ruby.sh
